### PR TITLE
Add Support for OS/2

### PR DESCRIPTION
**Pull request by andreaspeters**
Hi David,

thanks for your nice Game. It was very easy to port it to OS/2. I would be happy if you can merge it. Like u see, its just some small changes. :-)

Have a nice weekend,
Andreas

### CODE REVIEW

**Comment by davidjoffe** [comment]
Merging this finally! Thank you! But now we've just updated to SDL2 so I think the Makefile may need some changes!

**Comment by andreaspeters** [comment]
Thanks Dave! I will change it to SDL2. :-)

**Comment by davidjoffe** [comment]
Thanks! That would be wonderful

**Comment by davidjoffe** [comment]
Hi, I'm just drawing to this:

https://github.com/davidjoffe/dave_gnukem/issues/153

Thanks, sorry for any inconvenience

**Comment by andreaspeters** [comment]
No worries :-)

**Pull request merged**
